name: Test submitted code
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
	  matrix:
        include:
          - build: stable
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (rustup)
      run: rustup update stable --no-self-update && rustup default stable
