name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      issues: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test student code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cargo run

